In [1]:
cd /content/drive/MyDrive/SA_BC

/content/drive/MyDrive/SA_BC


In [2]:
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
df=pd.read_csv('data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df['diagnosis']=df['diagnosis'].map({'M':1,'B':0})

In [5]:
df

id  diagnosis  radius_mean  texture_mean  perimeter_mean  \
0      842302          1        17.99         10.38          122.80   
1      842517          1        20.57         17.77          132.90   
2    84300903          1        19.69         21.25          130.00   
3    84348301          1        11.42         20.38           77.58   
4    84358402          1        20.29         14.34          135.10   
..        ...        ...          ...           ...             ...   
564    926424          1        21.56         22.39          142.00   
565    926682          1        20.13         28.25          131.20   
566    926954          1        16.60         28.08          108.30   
567    927241          1        20.60         29.33          140.10   
568     92751          0         7.76         24.54           47.92   

     area_mean  smoothness_mean  compactness_mean  concavity_mean  \
0       1001.0          0.11840           0.27760         0.30010   
1       1326.0          0.08474           0.07864         0.08690   
2       1203.0          0.10960           0.15990         0.19740   
3        386.1          0.14250           0.28390         0.24140   
4       1297.0          0.10030           0.13280         0.19800   
..         ...              ...               ...             ...   
564     1479.0          0.11100           0.11590         0.24390   
565     1261.0          0.09780           0.10340         0.14400   
566      858.1          0.08455           0.10230         0.09251   
567     1265.0          0.11780           0.27700         0.35140   
568      181.0          0.05263           0.04362         0.00000   

     concave points_mean  ...  texture_worst  perimeter_worst  area_worst  \
0                0.14710  ...          17.33           184.60      2019.0   
1                0.07017  ...          23.41           158.80      1956.0   
2                0.12790  ...          25.53           152.50      1709.0   
3                0.10520  ...          26.50            98.87       567.7   
4                0.10430  ...          16.67           152.20      1575.0   
..                   ...  ...            ...              ...         ...   
564              0.13890  ...          26.40           166.10      2027.0   
565              0.09791  ...          38.25           155.00      1731.0   
566              0.05302  ...          34.12           126.70      1124.0   
567              0.15200  ...          39.42           184.60      1821.0   
568              0.00000  ...          30.37            59.16       268.6   

     smoothness_worst  compactness_worst  concavity_worst  \
0             0.16220            0.66560           0.7119   
1             0.12380            0.18660           0.2416   
2             0.14440            0.42450           0.4504   
3             0.20980            0.86630           0.6869   
4             0.13740            0.20500           0.4000   
..                ...                ...              ...   
564           0.14100            0.21130           0.4107   
565           0.11660            0.19220           0.3215   
566           0.11390            0.30940           0.3403   
567           0.16500            0.86810           0.9387   
568           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  \
0                  0.2654          0.4601                  0.11890   
1                  0.1860          0.2750                  0.08902   
2                  0.2430          0.3613                  0.08758   
3                  0.2575          0.6638                  0.17300   
4                  0.1625          0.2364                  0.07678   
..                    ...             ...                      ...   
564                0.2216          0.2060                  0.07115   
565                0.1628          0.2572                  0.06637   
566                0.1418          0.2218

In [6]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [7]:
mean_features = list(df.columns[1:11])
se_features = list(df.columns[11:21])
worst_features=list(df.columns[21:31])


In [8]:
mean_features.append('diagnosis')
se_features.append('diagnosis')
worst_features.append('diagnosis')

In [9]:
corr=df[mean_features].corr()

In [10]:
corr

diagnosis  radius_mean  texture_mean  perimeter_mean  \
diagnosis             1.000000     0.730029      0.415185        0.742636   
radius_mean           0.730029     1.000000      0.323782        0.997855   
texture_mean          0.415185     0.323782      1.000000        0.329533   
perimeter_mean        0.742636     0.997855      0.329533        1.000000   
area_mean             0.708984     0.987357      0.321086        0.986507   
smoothness_mean       0.358560     0.170581     -0.023389        0.207278   
compactness_mean      0.596534     0.506124      0.236702        0.556936   
concavity_mean        0.696360     0.676764      0.302418        0.716136   
concave points_mean   0.776614     0.822529      0.293464        0.850977   
symmetry_mean         0.330499     0.147741      0.071401        0.183027   
diagnosis             1.000000     0.730029      0.415185        0.742636   

                     area_mean  smoothness_mean  compactness_mean  \
diagnosis             0.708984         0.358560          0.596534   
radius_mean           0.987357         0.170581          0.506124   
texture_mean          0.321086        -0.023389          0.236702   
perimeter_mean        0.986507         0.207278          0.556936   
area_mean             1.000000         0.177028          0.498502   
smoothness_mean       0.177028         1.000000          0.659123   
compactness_mean      0.498502         0.659123          1.000000   
concavity_mean        0.685983         0.521984          0.883121   
concave points_mean   0.823269         0.553695          0.831135   
symmetry_mean         0.151293         0.557775          0.602641   
diagnosis             0.708984         0.358560          0.596534   

                     concavity_mean  concave points_mean  symmetry_mean  \
diagnosis                  0.696360             0.776614       0.330499   
radius_mean                0.676764             0.822529       0.147741   
texture_mean               0.302418             0.293464       0.071401   
perimeter_mean             0.716136             0.850977       0.183027   
area_mean                  0.685983             0.823269       0.151293   
smoothness_mean            0.521984             0.553695       0.557775   
compactness_mean           0.883121             0.831135       0.602641   
concavity_mean             1.000000             0.921391       0.500667   
concave points_mean        0.921391             1.000000       0.462497   
symmetry_mean              0.500667             0.462497       1.000000   
diagnosis                  0.696360             0.776614       0.330499   

                     diagnosis  
diagnosis             1.000000  
radius_mean           0.730029  
texture_mean          0.415185  
perimeter_mean        0.742636  
area_mean             0.708984  
smoothness_mean       0.358560  
compactness_mean      0.596534  
concavity_mean        0.696360  
concave points_mean   0.776614  
symmetry_mean         0.330499  
diagnosis             1.000000

In [11]:
prediction_vars=['radius_mean','perimeter_mean','area_mean','compactness_mean','concavity_mean','concave points_mean','radius_se','area_se','radius_worst','compactness_worst']

In [105]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size=0.15,random_state=1)


In [106]:
train_x=train[prediction_vars]
train_y=train['diagnosis']
test_x=test[prediction_vars]
test_y=test['diagnosis']


In [14]:
train_x

radius_mean  perimeter_mean  area_mean  compactness_mean  concavity_mean  \
501        13.82           92.33      595.9           0.16810         0.13570   
545        13.62           87.19      573.2           0.06747         0.02974   
62         14.25           96.42      645.7           0.20080         0.21350   
344        11.71           75.03      420.3           0.07281         0.04006   
457        13.21           84.10      537.9           0.05205         0.02772   
..           ...             ...        ...               ...             ...   
129        19.79          130.40     1192.0           0.15890         0.25450   
144        10.75           68.26      355.3           0.05139         0.02251   
72         17.20          114.20      929.4           0.18300         0.16920   
235        14.03           89.79      603.4           0.06945         0.01462   
37         13.03           82.61      523.8           0.03766         0.02562   

     concave points_mean  radius_se  area_se  radius_worst  compactness_worst  
501             0.067590     0.4751    39.05         16.01            0.39660  
545             0.024430     0.3460    31.24         15.35            0.15170  
62              0.086530     0.7036    60.78         17.67            0.62470  
344             0.032500     0.3446    24.53         13.06            0.11150  
457             0.020680     0.2084    17.58         14.35            0.10630  
..                   ...        ...      ...           ...                ...  
129             0.114900     0.4953    63.33         22.63            0.38610  
144             0.007875     0.2525    17.74         11.95            0.12230  
72              0.079440     0.5907    69.47         23.32            0.73940  
235             0.018960     0.2589    22.07         15.33            0.15130  
37              0.029230     0.1839    14.16         13.30            0.04619  

[483 rows x 10 columns]

In [15]:
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [16]:
model1 = RandomForestClassifier()
model2 = KNeighborsClassifier()
model3 = SVC()
#model4 = MLPClassifier

In [17]:
#Parameter tuning for RandomForest Classifier 
from sklearn.model_selection import GridSearchCV

In [19]:
parameters = {'max_depth':(1,2,3,4), 'n_estimators':(10,50,100,500)}
best_model=GridSearchCV(model1,parameters)

In [20]:
best_model.fit(train_x,train_y)

GridSearchCV(estimator=RandomForestClassifier(),
             param_grid={'max_depth': (1, 2, 3, 4),
                         'n_estimators': (10, 50, 100, 500)})

In [21]:
best_model.best_params_

{'max_depth': 4, 'n_estimators': 500}

In [22]:
model1.fit(train_x,train_y)

RandomForestClassifier()

In [24]:
prediction=model1.predict(test_x)

In [25]:
test_y

421    0
47     1
292    0
186    1
414    1
      ..
335    1
308    0
370    1
403    0
120    0
Name: diagnosis, Length: 86, dtype: int64

In [26]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y,prediction)

array([[51,  1],
       [ 5, 29]])

In [32]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
print(precision_score(test_y, prediction))
print(recall_score(test_y,prediction))
print(accuracy_score(test_y,prediction))


0.9666666666666667
0.8529411764705882
0.9302325581395349


In [33]:
model2.fit(train_x,train_y)

KNeighborsClassifier()

In [34]:
predict_model2=model2.predict(test_x)

In [35]:
predict_model2

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0])

In [38]:
confusion_matrix(test_y,predict_model2)

array([[50,  2],
       [ 8, 26]])

In [39]:
print(precision_score(test_y, predict_model2))
print(recall_score(test_y,predict_model2))
print(accuracy_score(test_y,predict_model2))

0.9285714285714286
0.7647058823529411
0.8837209302325582


In [40]:
model3.fit(train_x,train_y)

SVC()

In [41]:
predict_model3=model3.predict(test_x)

In [42]:
predict_model3

array([0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0])

In [43]:
confusion_matrix(test_y,predict_model3)

array([[52,  0],
       [ 8, 26]])

In [44]:
print(precision_score(test_y, predict_model3))
print(recall_score(test_y,predict_model3))
print(accuracy_score(test_y,predict_model3))

1.0
0.7647058823529411
0.9069767441860465


In [45]:
#Voting Classifier
from sklearn.ensemble import VotingClassifier
#create a dictionary of our models
estimators=[('RF', model1), ('KNN', model2), ('SVC', model3)]
#create our voting classifier, inputting our models
ensemble = VotingClassifier(estimators, voting='hard') 

In [48]:
#fit model to training data
ensemble.fit(train_x, train_y)

In [51]:
predict_ensemble = ensemble.predict(test_x)

In [52]:
predict_ensemble

array([1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0])

In [53]:
confusion_matrix(test_y,predict_ensemble)

array([[51,  1],
       [ 8, 26]])

In [54]:
print(precision_score(test_y, predict_ensemble))
print(recall_score(test_y,predict_ensemble))
print(accuracy_score(test_y,predict_ensemble))

0.9629629629629629
0.7647058823529411
0.8953488372093024


In [55]:
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(train_x,train_y)

Iteration 1, loss = 18.94192209
Iteration 2, loss = 5.89645343
Iteration 3, loss = 7.50870533
Iteration 4, loss = 5.42072396
Iteration 5, loss = 2.49239217
Iteration 6, loss = 4.16871865
Iteration 7, loss = 2.66709281
Iteration 8, loss = 1.28897131
Iteration 9, loss = 0.98329997
Iteration 10, loss = 0.70559336
Iteration 11, loss = 0.54745544
Iteration 12, loss = 0.58589229
Iteration 13, loss = 0.49943215
Iteration 14, loss = 0.43606401
Iteration 15, loss = 0.40240056
Iteration 16, loss = 0.31481526
Iteration 17, loss = 0.41067252
Iteration 18, loss = 0.33519099
Iteration 19, loss = 0.34753955
Iteration 20, loss = 0.31388109
Iteration 21, loss = 0.29139600
Iteration 22, loss = 0.31792645
Iteration 23, loss = 0.29882069
Iteration 24, loss = 0.30004440
Iteration 25, loss = 0.28518879
Iteration 26, loss = 0.29155512
Iteration 27, loss = 0.29586075
Iteration 28, loss = 0.29275949
Iteration 29, loss = 0.29129191
Iteration 30, loss = 0.28535569
Iteration 31, loss = 0.28315619
Iteration 32, lo

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

In [56]:
MLP_predict=clf.predict(test_x)

In [57]:
print(MLP_predict)

[1 0 0 1 1 1 1 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 1 1 1 0 1 0 0 0 1
 1 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1
 0 1 1 0 0 1 0 1 0 1 0 0]


In [58]:
confusion_matrix(test_y,MLP_predict)

array([[48,  4],
       [ 7, 27]])

In [60]:
print(precision_score(test_y, MLP_predict))
print(recall_score(test_y,MLP_predict))
print(accuracy_score(test_y,MLP_predict))

0.8709677419354839
0.7941176470588235
0.872093023255814


In [118]:
# save the model to disk
import pickle
filename1 = 'model1.sav'
filename2 = 'model2.sav'
filename3 = 'model3.sav'
pickle.dump(model1, open(filename1, 'wb'))
pickle.dump(model2, open(filename2, 'wb'))
pickle.dump(model3, open(filename3, 'wb'))
 
# some time later...
 
# load the model from disk
# loaded_model = pickle.load(open(filename, 'rb'))
# result = loaded_model.score(X_test, Y_test)
# print(result)

Still Working

In [66]:
train_x.shape

(483, 10)

In [114]:
# reshape data for an MLP input
# import numpy as np

# train_x = np.reshape(train_x, (1, ))
# train_y = np.reshape(train_y, (1, ))

# # normalize data
# train_images = train_images.astype('float32') / 255
# test_images = test_images.astype('float32') / 255

# convert labels to a one-hot vector
# from tensorflow.keras.utils import to_categorical

# train_x = to_categorical(train_x)
# test_y = to_categorical(test_y)

In [113]:
# # define network architecture
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import InputLayer
# from tensorflow.keras.layers import Dense

# MLP = Sequential()
# MLP.add(InputLayer(input_shape=(1,))) # input layer
# MLP.add(Dense(256, activation='relu')) # hidden layer 1
# MLP.add(Dense(256, activation='relu')) # hidden layer 2
# MLP.add(Dense(10, activation='softmax')) # output layer

# # summary
# MLP.summary()

In [111]:
# # optimization
# MLP.compile(loss='categorical_crossentropy',
#             optimizer='adam',
#             metrics=['accuracy'])

In [110]:
# # train (fit)
# MLP.fit(train_x, train_y, 
#         epochs=20, batch_size=128)

In [115]:
##Starting with streamlit

In [116]:
!pip install streamlit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 50.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 95.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.4/238.4 KB 22.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.0/79.0 KB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 164.8/164.8 KB 17.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.0/184.0 KB 19.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 KB 6.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.1/51.1 KB 6.0 MB/s eta 0:00:00
  Created wheel for validators: filename=validators-0.20.0-py3-none-any.whl size=19581 sha256=befeb150b1d9f55a72a38da7ec27c8cb9fa3b0e3e6a1b390f5ffa91090b11fe9
  Stored in directory: /root/.cache/pip/wheels/19/09/72/3eb7

In [117]:
import streamlit as st